[workspace]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
name = "8bit-adder"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
jlab = "jupyter lab --no-browser"
server = "fastapi run 8bit_adder/rpi_server.py"
[dependencies]
nbdev = ">=2.4.14,<3"
fastapi = ">=0.128.0,<0.129"
jupyterlab = ">=4.5.3,<5"
fastcore = ">=1.12.11,<2"

[pypi-dependencies]
gpiozero = ">=2.0.1, <3"
rpi-gpio = ">=0.7.1, <0.8"
