[workspace]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
name = "8bit-adder"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
nbdev = ">=2.4.14,<3"
fastapi = ">=0.128.0,<0.129"
jupyterlab = ">=4.5.3,<5"

[pypi-dependencies]
gpiozero = ">=2.0.1, <3"
